name: github-actions-js
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install eslint aibnb-base
        run: npm install eslint-config-airbnb-base
      - name: eslint
        run: make lint
      - name: test-coverage
        run: make coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_REPORT_ID }}
      
